"""Show what each solution asks the student to write, one blank at a time.

The answer pages under source/answers/ say what fills each blank. This says
something different: it starts from the lessons file as a student sees it, fills
one blank, and shows the diff that made. Read down a page and you see the edits
in the order a student makes them, each one on its own, with context that already
carries the blanks before it.

Applying the blanks in order has to end at the solutions file, and the tool
checks that it does. A blank that was missed, or applied in the wrong place,
shows up as a file that did not arrive.

It reads both files out of git at the commits keep.toml pins, the same as
tools/answers.py, and it shares that file's rule for what counts as a blank.

The pages are generated and not committed: this is a view for reading, not part
of the guide a student reads. `--build` runs Sphinx over them and prints where
the HTML landed.
"""

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

import answers
from bookpaths import book_root

OUT = "review"

CONF = '''"""Generated by tools/diffs.py. Edits here are overwritten."""

project = "What the student writes"
html_title = "What the student writes"
extensions = ["myst_parser"]
myst_enable_extensions = ["colon_fence", "deflist"]
html_theme = "furo"
'''


LESSON_NAME = re.compile(r"^L(\d+)([a-z]*)")


def order(path: str) -> tuple[int, int, str, str]:
    """Lesson order, which is not the alphabetical order git lists files in.

    L2 before L10, and L17a before L17b. A file whose name is not a lesson
    number, like LessonsDriveTrain, sorts after the lessons.
    """
    stem = Path(path).stem
    found = LESSON_NAME.match(stem)
    if not found:
        return (1, 0, "", stem)
    return (0, int(found.group(1)), found.group(2), stem)


def steps(blank: list[str], filled: list[str],
          found: list[tuple[int, int, int, int, bool]]) -> tuple[list[dict], list[str]]:
    """Each blank filled in turn, with the file before and after it.

    Every difference is applied, and only the blanks get a step: a javadoc line
    the lessons file carries and the solutions file does not is not something a
    student writes, but leaving it out means the file never arrives.

    Filling one changes how many lines the file has, so every difference after it
    sits somewhere else than the alignment said. The running offset is that
    difference, which is why they are applied forwards rather than in the reverse
    order that would avoid the bookkeeping: forwards is the order a student works
    in, and the context lines have to look like what they see.
    """
    state = list(blank)
    offset = 0
    out = []
    for i1, i2, j1, j2, is_blank in found:
        before = list(state)
        state[i1 + offset:i2 + offset] = filled[j1:j2]
        offset += (j2 - j1) - (i2 - i1)
        if not is_blank:
            continue
        out.append({
            "name": heading(blank[i1:i2]),
            "deleted": i2 - i1,
            "written": j2 - j1,
            "diff": "\n".join(difflib.unified_diff(
                before, list(state), lineterm="", n=3,
                fromfile="as the lesson leaves it", tofile="with this blank filled")),
        })
    return out, state


def heading(block: list[str]) -> str:
    """Every TODO marker in one run of blank lines, for the section title.

    tools/answers.py names a run after the first marker in it. Here the whole run
    is one edit, and a run can hold three markers, so all of them are named: the
    50 markers on the lessons line fall into 46 runs.
    """
    numbers = []
    for line in block:
        marker = line.find("TODO")
        if marker < 0:
            continue
        rest = line[marker + 4:].strip().rstrip(":").split(":")[0].strip()
        if rest and rest not in numbers:
            numbers.append(rest)
    if not numbers:
        return "A difference the lesson does not mark"
    if len(numbers) == 1:
        return "TODO " + numbers[0]
    return "TODO " + ", ".join(numbers[:-1]) + " and " + numbers[-1]


def lines(count: int, what: str) -> str:
    return f"{count} {what} line" + ("" if count == 1 else "s")


def page(path: str, filled_steps: list[dict], comments: int) -> str:
    written = sum(step["written"] for step in filled_steps)
    out = [f"# {Path(path).stem}", ""]
    out.append(f"`{path}`")
    out.append("")
    out.append(f"{len(filled_steps)} blank(s), {written} line(s) for the student to write.")
    out.append("")
    for step in filled_steps:
        out.append(f"## {step['name']}")
        out.append("")
        out.append(f"Delete {lines(step['deleted'], 'blank')}, write "
                   f"{lines(step['written'], 'real')}.")
        out.append("")
        out.append("```diff")
        out.append(step["diff"])
        out.append("```")
        out.append("")
    if not filled_steps:
        out.append("Nothing here for a student to write: the two lines differ only in comments.")
        out.append("")
    if comments:
        out.append(f"{comments} run(s) of comment lines differ as well, and are not blanks.")
        out.append("")
    return "\n".join(out)


def index(rows: list[tuple[str, int, int]], lessons: str, solutions: str,
          arrived: list[str]) -> str:
    out = ["# What the student writes", ""]
    out.append(f"Every blank on the lessons line at `{lessons}`, filled one at a time from the")
    out.append(f"solutions line at `{solutions}`. Each page is one file, each section one blank,")
    out.append("and each diff is one edit a student makes.")
    out.append("")
    out.append("The edits are grouped by where the two files differ, not by the TODO numbering, so")
    out.append("a run holding three markers is one edit and is named after all three. Where the")
    out.append("alignment puts a blank line in a different place, a line can also arrive one edit")
    out.append("earlier than the TODO that asks for it.")
    out.append("")
    out.append("| File | Blanks | Lines to write |")
    out.append("| --- | --- | --- |")
    for name, count, written in rows:
        out.append(f"| [{name}]({name}.md) | {count} | {written} |")
    out.append(f"| **Total** | **{sum(row[1] for row in rows)}** "
               f"| **{sum(row[2] for row in rows)}** |")
    out.append("")
    if arrived:
        out.append("These files did not come out the same as the solutions line after every blank")
        out.append("was applied, so something below is wrong: " + ", ".join(arrived) + ".")
    else:
        out.append("Applying every blank in order reproduces each solutions file exactly, which is")
        out.append("checked each time this is generated.")
    out.append("")
    out.append("```{toctree}")
    out.append(":maxdepth: 1")
    out.append(":hidden:")
    out.append("")
    for name, _, _ in rows:
        out.append(name)
    out.append("```")
    out.append("")
    return "\n".join(out)


def generate(lessons: str, solutions: str) -> tuple[dict[str, str], list[str]]:
    pages = {}
    rows = []
    wrong = []
    for path in sorted(answers.lesson_files(lessons), key=order):
        blank = answers.git("show", f"{lessons}:{path}").splitlines()
        filled = answers.git("show", f"{solutions}:{path}").splitlines()
        found = answers.differences(blank, filled)
        comments = sum(1 for *_, is_blank in found if not is_blank)
        filled_steps, arrived = steps(blank, filled, found)
        name = Path(path).stem
        if arrived != filled:
            wrong.append(name)
        pages[name + ".md"] = page(path, filled_steps, comments)
        rows.append((name, len(filled_steps), sum(s["written"] for s in filled_steps)))
    pages["index.md"] = index(rows, lessons, solutions, wrong)
    pages["conf.py"] = CONF
    return pages, wrong


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    pinned_lessons, pinned_solutions = answers.pins()
    parser.add_argument("--lessons", default=pinned_lessons,
                        help=f"the lessons commit (default {pinned_lessons}, from keep.toml)")
    parser.add_argument("--solutions", default=pinned_solutions,
                        help=f"the solutions commit (default {pinned_solutions}, from keep.toml)")
    parser.add_argument("--build", action="store_true", help="run Sphinx over the pages")
    args = parser.parse_args()

    out = book_root() / OUT / "source"
    pages, wrong = generate(args.lessons, args.solutions)
    out.mkdir(parents=True, exist_ok=True)
    for name, text in pages.items():
        (out / name).write_text(text, encoding="utf-8")
    written = sum(page.count("\n## ") for name, page in pages.items() if name != "index.md")
    print(f"{written} blank(s) across {len(pages) - 2} file(s), into {OUT}/source")

    if wrong:
        print("\nApplying every blank did not reproduce the solutions file for: "
              + ", ".join(wrong))
        return 1

    if args.build:
        html = book_root() / OUT / "build" / "html"
        finished = subprocess.run(
            ["sphinx-build", "-W", "-b", "html", str(out), str(html)],
            cwd=book_root(),
        )
        if finished.returncode:
            return finished.returncode
        print(f"\nOpen {html / 'index.html'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
